In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("D:/code/data/green/filtered_ppg_final_features.csv")

In [3]:
df.head(5)

             timestamp    rri  areaUp  areaDown  motion   hr
0  2026-06-10 11:31:27  500.0    1805     66610      99  120
1  2026-06-10 11:31:27  500.0    1349     52391     149  120
2  2026-06-10 11:31:27  500.0    1153     47928     189  120
3  2026-06-10 11:31:28  490.0     592     45356     338  122
4  2026-06-10 11:31:28  500.0     589    150810     130  120

In [4]:
df

                 timestamp     rri  areaUp  areaDown  motion   hr
0      2026-06-10 11:31:27   500.0    1805     66610      99  120
1      2026-06-10 11:31:27   500.0    1349     52391     149  120
2      2026-06-10 11:31:27   500.0    1153     47928     189  120
3      2026-06-10 11:31:28   490.0     592     45356     338  122
4      2026-06-10 11:31:28   500.0     589    150810     130  120
...                    ...     ...     ...       ...     ...  ...
82424  2026-06-11 17:09:04   590.0   92284    213010     269  101
82425  2026-06-11 17:09:05   760.0   12134    205505     269   78
82426  2026-06-11 17:09:06  1150.0   59513     87062     269   52
82427  2026-06-11 17:09:07   980.0   95485     77906     269   61
82428  2026-06-11 17:09:08   780.0   42211     64278     269   76

[82429 rows x 6 columns]